### ISSUE TITLE
Force remove accessories option

### ISSUE THREAD

**Issue by StumbleNOLA** [NorthernMan54/homebridge-tasmota#7]
**Is your feature request related to a problem? Please describe:**
While playing with sensors it is very easy to end up with lots of dead accessories, worse many of them end up with generic names so its not always clear which ones are which. Some way to force Homebridge to purge all non-responsive accessories would eliminate this issue.

**Describe the solution you'd like:**
Some setting or box in Homebridge settings that on the next reload only retains found devices.

**Describe alternatives you've considered:**
Full delete and reinstall of the plugin

**Additional context:**

**Comment by NorthernMan54** [comment]
I’m not sure which release of homebridge added this feature, but for at least 6 months now if you remove the plugin config from config.json it will delete all accessories associated with it. Then if you put the config back it will recreate all the devices.

But as I’m using home assistant mqtt autodiscovery to configure the devices, you need to remove the phantoms from their as well

Take a read of this guide

https://community.home-assistant.io/t/guide-how-to-remove-mqtt-entity-from-zigbee2mqtt-mosquitto-broker-and-home-assisntant/130564

Steps would be, clean up home assistant auto discovery records, then homebridge as the plugin will continue to create phantom devices based on the auto discovery records.

PS I had the same issue last week, due to testing out a couple of configs

**Comment by StumbleNOLA** [comment]
If you click on the "Homebridge Settings" in Homebridge (under the three dots), you can remove remove devices from the cache.

Closed as unnecessary.
